### ISSUE TITLE
Add crates.io badges

### ISSUE THREAD

**Issue by japaric** [rust-embedded/awesome-embedded-rust#1]
To all the crates that have been published to crates.io. The markdown to add is:

``` markdown
![crates.io](https://img.shields.io/crates/v/$CRATE.svg)
```

The result should look like this for `$CRATE = l3gd20`:

- [L3GD20] - SPI - Gyroscope - [Intro blog post][1&2] - ![crates.io](https://img.shields.io/crates/v/l3gd20.svg)

[L3GD20]: https://crates.io/crates/l3gd20
[1&2]: http://blog.japaric.io/wd-1-2-l3gd20-lsm303dlhc-madgwick/

**Comment by Caemor** [comment]
I should be able to do that on Saturday/Sunday.

**Comment by Caemor** [comment]
Can be closed?

**Comment by therealprof** [comment]
Sure. Haven't noticed that you didn't put a Fixes #1 in the PR description.
