### ISSUE TITLE
Where to put panic implementations?

### ISSUE THREAD

**Issue by jonas-schievink** [rust-embedded/awesome-embedded-rust#179]
There's quite a few panic implementations now, so I think it'd be useful to list them here. I'm not sure where exactly they should be put though, because some of them are platform-independent while others aren't. Personally I think these belong in their own section.

List of crates:

* [`panic-halt`](https://github.com/korken89/panic-halt): Halts the processor on panics
* [`panic-abort`](https://github.com/japaric/panic-abort): Causes an abort on panics (nightly-only)
* [`panic-ramdump`](https://github.com/therealprof/panic-ramdump): Writes the panic message into the beginning of RAM and enters an infinite loop; the message can be extracted by attaching a debugger (Cortex-M only)
* [`panic-semihosting`](https://github.com/rust-embedded/panic-semihosting): Prints the panic message via semihosting to an attached debugger (Cortex-M only)
* [`panic-itm`](https://github.com/rust-embedded/panic-itm): Prints the panic through the chip's ITM to a debugger attached to the SWO pin (Cortex-M with ITM only)

**Comment by jonas-schievink** [comment]
Forgot about [`panic-never`](https://docs.rs/panic-never).

**Comment by Disasm** [comment]
Maybe these deserve to be in the panic-section too:
* [`no-panic`](https://crates.io/crates/no-panic)
* [`dont_panic`](https://crates.io/crates/dont_panic) + [`dont_panic_slice`](https://crates.io/crates/dont_panic_slice)

**Comment by berkus** [comment]
PR is ready for review.

**Comment by BartMassey** [comment]
`panic-rtt` ?

**Comment by berkus** [comment]
@BartMassey pls review
