### ISSUE TITLE
Update Espressif story

### ISSUE THREAD

**Issue by chrysn** [rust-embedded/awesome-embedded-rust#198]
The abandonment note on [esp-rs](https://github.com/emosenkis/esp-rs) in favor of [building rustc on Espressif's LLVM](http://quickhack.net/nom/blog/2019-05-14-build-rust-environment-for-esp32.html) and the [related quickstart repo](https://github.com/MabezDev/xtensa-rust-quickstart) indicate that mrustc is not the way to go on ESP32 / ESP8266 / Xtensa cores any more.

I don't have the devices at hand or experience with that platform, but the current information in this repo seems to be outdated. @emosenkis or @rahul-thakoor, could you maybe have a look at that?

**Comment by xoac** [comment]
#223

**Comment by David-OConnor** [comment]
Any word on this?

**Comment by emosenkis** [comment]
#282

**Comment by emosenkis** [comment]
Merged - I think this can be closed
