### ISSUE TITLE
List of general purpose no-std crates

### ISSUE THREAD

**Issue by japaric** [rust-embedded/awesome-embedded-rust#2]
The list of no-std crates is currently empty!

We have collected a list of such crates in rust-lang-nursery/embedded-wg#12 but the list hasn't been
updated in a long time. It now probably contains deprecated crates, crates that are no longer under
active development or crates that never achieved a "complete" (published and documented) state.

Help us review that old list and make a new list with the best parts of the old one. Also, it would
be great if the new list was split in categories to make it easier for readers to find what they are
looking for. [The awesome Rust list][awesome-rust] may provide some inspiration for this
categorization task.

[awesome-rust]: https://github.com/rust-unofficial/awesome-rust

**Comment by memoryruins** [comment]
Common categories in rust-lang-nursery/embedded-wg#12 to get a rough outline:

- Data structures
- Debugging
  - Logging
  - Testing
- Encoding / Decoding
  - Binary
  - Protocol
- Graphics
- Math
- Networking
- Text
  - CStr
  - Unicode

Many of the parsing / encoding crates share similarities in their purpose, as well as crates tagged with memory management, alignment, and data structure, so it may be possible to group into sub/shared categories.

**Comment by mathk** [comment]
Ping from triage: Is this "issue" still an "issue" ? I can see a lot in the no_std list

**Comment by jamesmunns** [comment]
I don't think it is anymore :) Closing.
