### ISSUE TITLE
Drone-os

### ISSUE THREAD

**Issue by elpiel** [rust-embedded/awesome-embedded-rust#208]
I came a cross this library yesterday, thought I might put it here as I didn't see it here:
https://github.com/drone-os 
I'm not very good with embedded so I am not sure which projects should be listed in here.

**Comment by xoac** [comment]
@elpiel [Tock](https://www.tockos.org/) is added in https://github.com/xoac/awesome-embedded-rust/tree/master#books-blogs-and-training-materials But I think there could be new section with rust RTOSes?

**Comment by elpiel** [comment]
Well I've just opened a PR, should make it easier to reason about in the PR instead of the issue and get feedback faster I guess.
