### ISSUE TITLE
Is the "Adventures in Motion Control" blog series relevant here?

### ISSUE THREAD

**Issue by Michael-F-Bryan** [rust-embedded/awesome-embedded-rust#210]
Over the last month or two I've been working on a blog series focused around designing and implementing a real-world embedded system ([intro][1]/[all posts][2]), primarily based on the experience I've gained programming CNC machines in the wild.

There are a lot of resources online based on the low-level details like peripheral crates and how to get code running, but I haven't seen much in the way of high-level architecture or how to make these sorts of embedded systems in a scalable way. That's what I'm trying to address with the aforementioned blog series.

However, the implementation itself is written using WASM instead of a real embedded device (everyone has a browser, not everyone has a STM32 dev board handy). 

Is this sort of resource still relevant to the *Awesome Embedded Rust* list?

[1]: http://adventures.michaelfbryan.com/posts/announcing-adventures-in-motion-control/
[2]: http://adventures.michaelfbryan.com/tags/adventures-in-motion-control/

**Comment by therealprof** [comment]
@Michael-F-Bryan Love your blog posts but I think the aer is more useful for resources which make continuous progress and are directly useable. Having said that it would be great to feature them on the blog https://github.com/rust-embedded/blog and if you ever have something like a full example application or useful crate coming out of it we'd be very happy to put in on aer.

**Comment by Michael-F-Bryan** [comment]
> if you ever have something like a full example application or useful crate coming out of it we'd be very happy to put in on aer

Thanks, I hadn't thought about linking to the final application as a kind of "showcase".

My blog series is definitely more hand-wavy and less directly usable than a crate or self-contained article on a single technical topic, hence why I wasn't 100% sure whether it'd be relevant to the list.

**Comment by therealprof** [comment]
We also have a showcase now: https://github.com/rust-embedded/showcase 😄
