### ISSUE TITLE
Cortex-M Quickstart needs attention.

### ISSUE THREAD

**Issue by LucianoMoretti** [rust-embedded/awesome-embedded-rust#226]
Sorry if this is the wrong place:
The Cortex-M Quickstart guide Docs.rs build 0.3.4 is failing with the following:
`
error[E0658]: The attribute 'panic_implementation' is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/panic-semihosting-0.3.0/src/lib.rs:71:1
   |
71 | #[panic_implementation]
   | ^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(custom_attribute)] to the crate attributes to enable
`

Also, the last built version (0.3.1) references using Nightly, which is no longer required for the Cortex-M.

**Comment by jonas-schievink** [comment]
Quickstart is hosted at https://github.com/rust-embedded/cortex-m-quickstart. It is no longer published to crates.io (as it isn't a crate). The repo is up to date.

**Comment by jamesmunns** [comment]
I'm going to close this issue. Let me know if anyone thinks we should re-open!
