### ISSUE TITLE
Add Sipeed as Vendor

### ISSUE THREAD

**Issue by wucke13** [rust-embedded/awesome-embedded-rust#242]
Sipeed offers quite a few interesting very low cost RISC V boards, like the _Sipeed Longan Nano_.
The cpu - a GD32 - is officially supported by the RISC V Team, in this crate: https://github.com/riscv-rust/gd32vf103xx-hal

Adding Sipeed and a link to that Repo would be nice, so that people don't think there board isn't supported after they looked hear.

**Comment by Disasm** [comment]
PR would be great!
