### ISSUE TITLE
areWeEmbeddedYet.rs?

### ISSUE THREAD

**Issue by tanekere** [rust-embedded/awesome-embedded-rust#257]
Just a suggestion. Let’s make this a arewe_yet website. 

It would be a more “pragmatic rust” way of doing this. Generating markdown-based website from the readme won’t be hard and I am willing to do it. Forking another arewe_yet website that already has the ci setup would be good too. 

Also the title is like that just for readability. I know snake case is better.

**Comment by jamesmunns** [comment]
If you're interested in building this, I'd be happy to take a look!

**Comment by niclashoyer** [comment]
I had a go at it and forked arewewebyet: https://github.com/niclashoyer/areweembeddedyet

Two major problems arose:

 - the structure behind arewewebyet pulls all informations from crates.io, so the build failed for each package that was not yet published
 - parsing the readme was more difficult than I thought, so I just started with two topics, copying sections by hand: board support and hal implementations

The getting started section on the front page needs work, it still references the links related to web. But at least `it's something` :rainbow:

https://niclashoyer.github.io/areweembeddedyet/

**Comment by berkus** [comment]
A simpler way would be to use the website as either redirect or just renderer for the readme, although the value for such approach is greatly diminished.
