### ISSUE TITLE
Looking for collaborators

### ISSUE THREAD

**Issue by japaric** [rust-embedded/awesome-embedded-rust#3]
To help me maintain this list by merging the PRs that are submitted by the community.

**Comment by rahul-thakoor** [comment]
I want to help!

**Comment by berkus** [comment]
Count me in. Will PR entire berkus/awesome-embedded-rust soon.

**Comment by berkus** [comment]
Posted the [PR](https://github.com/rust-embedded/awesome-embedded-rust/pull/12)

**Comment by japaric** [comment]
I think we have plenty of reviewers at the moment so I'm going to close this.
