### ISSUE TITLE
RF24 support

### ISSUE THREAD

**Issue by ArthurFleischman** [rust-embedded/awesome-embedded-rust#308]
Im an arduino user, diving into the depper lever of embedded, and would be useful to have the most common radio module support, the nordic rf24l01.... I hope I've helped!

**Comment by eldruin** [comment]
If you look at the list, you can see that there are 2 drivers for the nrf24l01:
- https://crates.io/crates/embedded-nrf24l01
- https://github.com/maikelwever/nrf24l01
