### ISSUE TITLE
Removal of Badges

### ISSUE THREAD

**Issue by memoryruins** [rust-embedded/awesome-embedded-rust#32]
Previously opened an issue about formatting and badge use on the awesome-rust list https://github.com/rust-unofficial/awesome-rust/issues/419.

For awesome-embedded-rust, I propose continuing with the format we have now, which is the "simpler alternative" in the above link, except without any graphical badges (the graphical logo at the top looks fantastic, however). Removing the noise of misaligned badges, It's easier to read and especially to load. Bringing up now before the lists begin to grow, especially with the many crates to be added for no-std #2.

**Comment by therealprof** [comment]
@memoryruins So you're proposing to revert #1? I'm more in favour to go with #20 instead which would also remove a lot of the badges from the entry page to unclutter the entry page.

**Comment by memoryruins** [comment]
Ah yes, my bad. I would have left a comment there if I saw earlier. Many awesome lists do without, and the ones that add structure and alignment, e.g https://github.com/bnb/awesome-hyper, still experience sluggish load times.

I’m also in favor of splitting certain sections into their own pages, and less badges may be best in the long run there as well.

**Comment by RandomInsano** [comment]
Exhuming this thread from the dead, I do think removing the badges is a good plan. @japaric what was the original reason to add them? They’re neat but was there other reasons than the coolness factor?

The practical reason I can see is to check for newer versions of crates in one place.

**Comment by eldruin** [comment]
Aside from the coolness factor, it has been useful to me to distinguish which projects have a published crate and which ones do not.
Personally, for the ones with a published crate I assume that the library is usable, there is a reliable versioning and a somewhat thought-through API, even if it is not complete.
Without a published crate I expect more of an unstable and not very usable project.

The slow loading is somewhat annoying, though. Would this be better if we used pngs instead of svgs?

**Comment by therealprof** [comment]
@eldruin If this is done right (haven't checked) SVGs would be vastly smaller than PNGs. I think the main problem here is that each image is individually loaded from the server...

**Comment by RandomInsano** [comment]
> vastly smaller

Depends on the resolution of the *rendered* rendered image. A one pixel bitmap beats them all. :P

It could be the browser implementation of parsing and walking a new complex data structure each image that is the delay we’re seeing.

**Comment by therealprof** [comment]
Sorry, but I don't see **any** improvement here. It neither renders faster for me nor would I consider it a fattening the already big page further a worthwhile tradeoff.

**Comment by RandomInsano** [comment]
Really?! Can you open your browsers profiler, disable caching (both FF and Chrome support this) and check the networking timeline?

**Comment by Israel-Laguan** [comment]
As there is already a failed test for this change, maybe this PR needs to be closed.
