### ISSUE TITLE
Section about embedded tooling

### ISSUE THREAD

**Issue by barafael** [rust-embedded/awesome-embedded-rust#360]
Should this list include a section on things like probe-rs, flip-link, cargo-bloat, ... ?

**Comment by eldruin** [comment]
Sure. Do you mean something different to the [Tools](https://github.com/rust-embedded/awesome-embedded-rust#tools) section?
cargo-bloat and probe-rs are missing here indeed. A PR adding them would be great.

**Comment by barafael** [comment]
Never mind, i didn't see that! Can be closed :)
