### ISSUE TITLE
Add full list of LM75-equivalent devices supported by the linked LM75 library

### ISSUE THREAD

**Issue by DeflateAwning** [rust-embedded/awesome-embedded-rust#442]
The full list of devices equivalent to the LM75, per the library's README, are:

> This driver is also compatible with at least [LM75A](https://www.nxp.com/docs/en/data-sheet/LM75A.pdf), [LM75B, LM75C](http://www.ti.com/lit/ds/symlink/lm75b.pdf), [AT30TS75A](http://ww1.microchip.com/downloads/en/DeviceDoc/Atmel-8839-DTS-AT30TS75A-Datasheet.pdf), [DS1775](https://datasheets.maximintegrated.com/en/ds/DS1775-DS1775R.pdf), [DS75](https://datasheets.maximintegrated.com/en/ds/DS75.pdf), [DS7505](https://datasheets.maximintegrated.com/en/ds/DS7505.pdf), [G751](http://www.gmt.com.tw/product/datasheet/EDS-751.pdf), [MAX7500/1/2/3/4](https://datasheets.maximintegrated.com/en/ds/MAX7500-MAX7504.pdf), [MAX6625](https://datasheets.maximintegrated.com/en/ds/MAX6625-MAX6626.pdf), [MCP9800/1/2/3](http://ww1.microchip.com/downloads/en/DeviceDoc/21909d.pdf), [STDS75](https://www.st.com/resource/en/datasheet/stds75.pdf), [TCN75](http://ww1.microchip.com/downloads/en/DeviceDoc/21490D.pdf), [PCT2075](https://www.nxp.com/docs/en/data-sheet/PCT2075.pdf).

It would be awesome if this list was included in this repo for easied Ctrl+F!

**Comment by eldruin** [comment]
Sounds useful to me, although it might make the entry very long. Could you send the change in a PR?

**Comment by DeflateAwning** [comment]
Done! Doesn't look the best, but hardly out of place at all imo
