### ISSUE TITLE
Adding non development boards to board support crates section??

### ISSUE THREAD

**Issue by JoshMcguigan** [rust-embedded/awesome-embedded-rust#65]
I wrote a board support crate, [betafpv-f3](https://github.com/JoshMcguigan/betafpv-f3), for a drone flight controller. Currently, the board support crates section of this repo says `Crates tailored for specific development boards.`. 

Is there any interest in listing board crates for more specialized boards like this? I was thinking possibly an `Other` category could be used to group them separately from the existing boards, but I wanted to discuss it before making a PR.

**Comment by therealprof** [comment]
In my opinion specific relates to the word boards more than it does to the term development. If the board is readily available it would be acceptable for inclusion. OTOH I do very much like the idea of yours to add a single/special purpose section, too, but making it more explicit than "other".

**Comment by JoshMcguigan** [comment]
I submitted a PR just to keep this moving forward, but I wasn't actually sure if you were thinking the `Special Purpose` section would be within the existing `Board Support Crates` section, or if it would be it's own section perhaps listed just after the `Board Support Crates` section? 

I can update the PR as needed based on further discussion here.

**Comment by therealprof** [comment]
That is okay for now. I'm thinking about restructuring this a bit anyway at some point.

**Comment by JoshMcguigan** [comment]
Great, thanks for the merge. I'll close this issue.
