### ISSUE TITLE
Decide what to do with HD44780/clerk crate

### ISSUE THREAD

**Issue by therealprof** [rust-embedded/awesome-embedded-rust#69]
As pointed out by @JohnDoneth, @kunerd crate [HD44780](http://github.com/kunerd/clerk) is doing custom bitbanging via sysfs instead of using the `embedded-hal` traits which means that this driver does not fulfil the criteria for a "driver crate" as mentioned on the page:

> Platform agnostic crates to interface external components. These crates use the embedded-hal interface to support all the devices and systems that implement the embedded-hal traits.

We could move it down a section to the `no_std` crates.

@kunerd What do you think?

**Comment by kunerd** [comment]
I started [porting](https://github.com/kunerd/clerk/issues/32) the lib to use the `embedded-hal` traits some time ago, but had some issues and some discussions started on how to handle parallel ports within `embedded-hal`. After that I unfortunately haven't had enough time to do further work on this. I also haven't tracked the discussions on parallel ports, so I don't know the current state on that. But, I have not a problem with moving `clerk` to `no_std`.

**Comment by therealprof** [comment]
@kunerd Would you mind creating a PR for the move between sections?

**Comment by berkus** [comment]
It's in the "WIP drivers" section, asking for help in porting, so it seems to be in the right spot for now.
